### ISSUE TITLE
Sensor data validation

### ISSUE THREAD

**Issue by LaStrada** [LaStrada/pyfreshintellivent#1]
Not all from the sensor data characteristic make any sense. A list of done/wanted sensor readings:

- [x] RPM
- [x] Mode (e.g. humidity)
- [x] Temperature (need validation)
- [ ] Humidity
- [x] Light
- [x] VOC (Air Quality)

Example outputs (one reading per line):
```
O   M   H  H    V  V    L  L    R  R            S  T    T
N   O   U  U    O  O    I  I    P  P            E  E    E
    D   M  M    C  C    G  G    M  M            C  M    M
    E                   H  H                    S  P    P
                        T  T
00 00   5a 01   18 05   55 06   00 00   2b 05   00 19   00
00 00   E4 00   45 04   4A 06   00 00   32 04   00 18   00
10 34   2e 01   9b 05   ba 0c   22 06   37 05   3b 1b   00
```

**Comment by LaStrada** [comment]
Temperature seems right. But still need some validation.

**Comment by LaStrada** [comment]
After reading `pycalima`'s approach to calculate the humidity I tried the same thing:
https://github.com/PatrickE94/pycalima/commit/39a59adc24233f340f531b58b2acfdab1bb75d08

I've seen values up to about `2200`, but when using log2 I get 11.10. If I then multiplies with 10 it's > 100%. Not sure if this value is a relative humidity value. As mentioned in the `pycalima` repository it's probably a good idea to look into what sensor they're using.

Values last 24H based on byte 7+8 (int) / 10:
<img width="1143" alt="image" src="https://user-images.githubusercontent.com/270292/131916825-8bf1702b-e33e-4ca5-ac9a-19bc36931256.png">

**Comment by LaStrada** [comment]
Temperature seems right. Compared to another sensor (sorry for terrible resolution on this graph):
<img width="496" alt="image" src="https://user-images.githubusercontent.com/270292/131917029-b0b1c998-f533-4126-9dd3-1d085a3bb5eb.png">
If this is correct, temperature doesn't have any decimals.

**Comment by LaStrada** [comment]
VOC seems to be correct, not sure about the scale, but the mode of the fan (mode = 52) reflects these spikes:
<img width="2288" alt="image" src="https://user-images.githubusercontent.com/270292/131917325-404888cf-9fed-4898-a8ab-9fa97ffe7dba.png">

**Comment by LaStrada** [comment]
Light seems to be right as well. And same with VOC, not sure about the scale. The mode seems to reflect this (mode = 34):
<img width="2289" alt="image" src="https://user-images.githubusercontent.com/270292/131917416-d9ed2c9f-6dcd-41a6-b504-7d07804e9cbd.png">

**Comment by LaStrada** [comment]
Humidity might be `log(value / 10) * 10`. Need more data to be able to validate.

**Comment by skynetforcats** [comment]
> 
> 
> Humidity might be `log(value / 10) * 10`. Need more data to be able to validate.

Just got this installed and didn't read this post until after some investigation.
But I arrived at this.

```
44:00:08:0e:ad:08:00:00:00:00:9d:08:00:1a:00
   M  H     T     L
   O  U     E     I
   D  M     M     G
   E        P     H
            ?     T
```
Where humidity is the natural log of the short times 10:
`Humidity = ln(value)*10`

Edit:
@LaStrada You may be correct about the humidity. I think I used base 10 instead of base 2 with your formula. With base 2 it matches a bit better with my other sensors using `log(value / 10) * 10`

**Comment by LaStrada** [comment]
Here is a comparison between my Airthings Wave Mini + Fresh Sky Intellivent (using `log(value / 10) * 10`) the past 24h. The Airthings Wave Mini is placed 1 meter away from the shower, so I guess it won't be able to measure the exact same humidity levels as the ventilation fan, but for me this looks spot on!
<img width="1094" alt="image" src="https://user-images.githubusercontent.com/270292/137695838-8e3e4c9d-f19d-41d6-bdac-4ee4f689b248.png">
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/270292/137695882-54052bda-0f71-465f-a024-15dc7fb7e277.png">

**Comment by skynetforcats** [comment]
How about temperature? It seems that there are two values that could be temp. The values are always very close to each other. Sometimes 100% identical.

```
44:00:08:0e:ad:08:00:00:00:00:9d:08:00:1a:00
   M  H     T     L           T
   O  U     E     I           E
   D  M     M     G           M
   E        P     H           P
            ?     T           ?
```

**Comment by skynetforcats** [comment]
> 
> 
> Here is a comparison between my Airthings Wave Mini + Fresh Sky Intellivent (using `log(value / 10) * 10`) the past 24h. The Airthings Wave Mini is placed 1 meter away from the shower, so I guess it won't be able to measure the exact same humidity levels as the ventilation fan, but for me this looks spot on! 

Mine reads about 10% higher humidity than any other sensors I have. But otherwise the graphs follow eachother nicely.

I made another graph of temp1 and temp2 according to below. It looks like temp2 is some kind of moving average of temp1. But for some reason my values have these extreme spikes that I can't really make sense of. Maybe from someone else's vents or cooking hoods in my building.

```
44:00:08:0e:ad:08:00:00:00:00:9d:08:00:1a:00
   M  H     T     L           T
   O  U     E     I           E
   D  M     M     G           M
   E        P     H           P
            1     T           2
```

![image](https://user-images.githubusercontent.com/36438756/141463647-93d511a4-f527-4f84-944b-d3ce5388d552.png)

**Comment by LaStrada** [comment]
Need to revisit this, but we should start from scratch.
