### ISSUE TITLE
HA addon?

### ISSUE THREAD

**Issue by dennisgranasen** [LaStrada/pyfreshintellivent#11]
Hey, this is interesting. Any chance this is becoming an addon for home assistant?

**Comment by LaStrada** [comment]
I'm no home assistant expert, but it should be possible to integrate it directly to the Bluetooth integration.

I am using an old RPI to fetch this data and passes it over to home assistant. Also fetches data from HA and uses this data to adjust the speed on the fan etc. But this is just something I put together to test things, nothing I will publish right now. It would have been nice to convert it to MQTT or just make the code clean / re-usable for others.

**Comment by LaStrada** [comment]
After looking into the dev docs to HA + the new 2022.9 release, it seems like I can extend the Bluetooth range by using [bluetooth proxy](https://esphome.io/components/bluetooth_proxy.html). I have never created an integration from scratch before, and never touched/looked into the BLE integration in HA. So I don’t think I’m the right person to implement this into HA. But will be happy to do the changes needed to make this framework work with HA.

Also noticed that HA uses Bleak as BLE framework, so this repo might need some changes to be able to be used in HA.

**Comment by tedenda** [comment]
I also have a SKY and would really like if it could be integrated into Home Assistant! 
I haven't done any integrations either so not much help from me. 
I can of course help with testing if you decide to try!

**Comment by LaStrada** [comment]
With the new Home Assistant 2022.10 update, it's now supported to have active BLE connections (connect to the device + sending data + read data). That was needed to be able to do this kind of integration. Not sure if this repo directly can be used in Home Assistant, but at least the "findings" (authentication, characteristics, parsing sensor values, modes etc) can be used.

I will look into creating an integration, but my time is limited for the rest of the year. What I can do is to publish what I'm using right now as an example. It's a python script that fetches data from HA (constant speed, mode RPMs etc) and sends it to the fan. This is running inside a loop and tries to fetch/send data every 30 sec. Just need to modify it a bit so it can easily be reused by anyone. But it can't run on the HA machine itself, I'm using a separate PI to run this script, because the script need BLE communication 100% of the time.

**Comment by tedenda** [comment]
If you start doing a integration maybe someone from the HA community can step in and help?
We can at least hope so!

Following this closely.

**Comment by angoyd** [comment]
@LaStrada if you setup the Project and the basis for the HA integration/component I can help with testning and continuous Development.

**Comment by angoyd** [comment]
@LaStrada do you have any experience in making HA components? I have been looking into the existing ones, and there is one for Fjäråskupan (https://github.com/home-assistant/core/tree/dev/homeassistant/components/fjaraskupan) that looks very much like the Intellivent maybe we can use that as a boilerplate if you dont have any other ideas?

**Comment by LaStrada** [comment]
Not directly, but have reviewed a few PRs and I have read a lot about it lately. With the new BLE proxy with ESPHome it looks really promising. My goal is to start on something this month, but not sure when I'll finish.

Will create a separate repo for it or a fork of HA and post it here. Will definitely need some help!

I'm not sure how changing modes will be handled. My first thought was maybe add services, but I need to just try it out. Or just do a first version with basic sensors (temperature, humidity, rpm).

**Comment by LaStrada** [comment]
@angoyd Looked into the `fjaraskup` repo and HA integration, and hopefully we can reuse some of the code! I have never created a setup/config flow before, and it was very helpful to see how they have done it.

**Comment by angoyd** [comment]
@LaStrada cool maybe er can setup som way to commnicate in a little more quick way than github :) Any suggestions?

**Comment by LaStrada** [comment]
I created a Discord server:
https://discord.gg/egmJmyVn

**Comment by tedenda** [comment]
@LaStrada I tried to join discord channel but the link seems to be outdated or something?

**Comment by LaStrada** [comment]
@tedenda https://discord.gg/vQPc75pm

**Comment by tedenda** [comment]
@dennisgranasen Have you tried the HA-Addon that is under development?
Look over here: [Fresh Intellivent Sky integration for Home Asssistant](https://github.com/angoyd/freshintelliventHacs)

**Comment by dennisgranasen** [comment]
Yes @tedenda. I have it installed, and I am following the development. The code is under construction and currently has some issues with connection stability. I'm pretty confident where the errors are in regards to the disconnects, and I have pointed it out. Unfortunately there isn't a lot of coding action going on at the moment, I suppose life happens.

Anyway, I'd contribute myself and write the code if I had setup a reasonable debug environment at home. Currently that isn't the case though - so for now I'm just waiting around to see if @angoyd (or someone else) finds the time to implement the necessary changes.

**Comment by tedenda** [comment]
Just wanted to check!

I have contributed both to this library and HA-addon when time is available. I mostly contribute things like documentation, I don't have the skills of advanced python programming. I know there have been personal "issues" and life is always most important. If you have some things you can fix please open issues, create PR's or discuss.

**Comment by tedenda** [comment]
@LaStrada I think you can close this issue now when README.md is updated with link to freshintelliventHacs repo.

**Comment by LaStrada** [comment]
HA addon is in the making using this framework:
https://github.com/angoyd/freshintelliventHacs
